---
#-------------------------------
# General Site Settings

title: Juan Manjarres
logo:
author: juan manjarres
description: software developer, computer science student
email: juan.manjarres@usask.ca
phone: +1 (639) 994-9453
address: Saskatoon, SK
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Juan, <br> Software Developer

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-linkedin", link: "#" }
  - { icon: "ti-github", link: "#" }
#-------------------------------
# About (Section and Page)

# About Section
blurb: I am currently in my last semester of Computer Science at the University of Saskatchewan, <br> I have a passion for technology and have worked as a Mobile Developer for the past two summers. Some of my other interests also include Human Computer Interaction, UI/UX design, and Operating Systems.
blurb-btn-link: "/about"
blurb-btn-name: know more

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Flutter/Dart, color: "#fdb157", value: "90%" }
  - { name: C, color: "#9473e6", value: "60%" }
  - { name: Web Programming, color: "#bdecf6", value: "50%" }
  - { name: Java, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Summer Mobile Developer,
      icon: "icon-1.png",
      date: "May 2022 - Aug 2022",
      organization: "Troo Corp",
    }
  - {
      name: Summer Mobile Developer,
      icon: "icon-2.png",
      date: "May 2021 - Aug 2021",
      organization: "Troo Corp",
    }
  - {
      name: Store Associate,
      icon: "icon-3.png",
      date: "July 2020 - May 2021",
      organization: "Winners",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: B.Sc. Honours in Computer Science,
      date: "April 2023",
      organization: "University of Saskatchewan",
    }
  - {
      name: Bachiller Acad&eacute;mico,
      date: "December 2017",
      organization: "Liceo Segovia",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: UI Design,
      icon: ti-palette,
      description: "Prototyped on Figma, understanding basic UI principles and design",
      active: ,# Add true to select section
    }
  - {
      name: Mobile Development,
      icon: ti-mobile,
      description: "Experience working for Troo as a Mobile Developer, with side projects on Android",
      active: true, # Add true to select section
    }
  - {
      name: Full Stack Development,
      icon: ti-panel,
      description: "Familiar with Javascript, HTML, node.js, MongoDB and other web technologies",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: juan.manjarres@usask.ca
